import type { Pattern } from './retrievalTypes'

export const MODALITY_PATTERNS: Pattern[] = [
  {
    id: 'can_cant', name: 'Могу / не могу', category: 'Модальность', level: 'A2',
    form: 'can / can’t + verb', meaning: 'Способность, возможность или невозможность.',
    repair: 'После can/can’t используй начальную форму глагола без to.',
    full: /\b(can|can't|cannot)\s+[a-z]+\b/, partial: /\b(can|can't|cannot)\b/,
    drills: [
      { cue: 'Я могу помочь тебе вечером.', models: ['I can help you this evening.', 'I can give you a hand tonight.'] },
      { cue: 'Она не умеет водить.', models: ["She can't drive.", 'She cannot drive.'] },
      { cue: 'Ты можешь открыть окно?', models: ['Can you open the window?', 'Can you open the window for me?'] },
      { cue: 'Мы можем встретиться завтра.', models: ['We can meet tomorrow.', 'We can get together tomorrow.'] },
      { cue: 'Я не могу сейчас говорить.', models: ["I can't talk right now.", 'I cannot speak at the moment.'] },
      { cue: 'Он очень хорошо плавает.', models: ['He can swim very well.', 'He is a very good swimmer.'] },
      { cue: 'Можно здесь припарковаться?', models: ['Can we park here?', 'Can I park here?'] },
      { cue: 'Я не могу найти ключи.', models: ["I can't find my keys.", 'I cannot find my keys anywhere.'] },
      { cue: 'Она может прийти позже.', models: ['She can come later.', 'She can join us later.'] },
      { cue: 'Мы не можем это сделать сегодня.', models: ["We can't do it today.", 'We cannot get it done today.'] },
    ],
  },
  {
    id: 'have_to', name: 'Нужно / приходится', category: 'Модальность', level: 'A2',
    form: 'have to / has to + verb', meaning: 'Необходимость из-за правил, обстоятельств или ситуации.',
    repair: 'Для внешней необходимости используй have to / has to + глагол.',
    full: /\b(have|has|had)\s+to\s+[a-z]+\b|\bdon't have to\b|\bdoesn't have to\b/, partial: /\b(have|has|had)\s+to\b/,
    drills: [
      { cue: 'Мне нужно уйти в шесть.', models: ['I have to leave at six.', "I've got to leave at six."] },
      { cue: 'Ей приходится вставать рано.', models: ['She has to get up early.', 'She has to wake up early.'] },
      { cue: 'Нам нужно закончить сегодня.', models: ['We have to finish today.', 'We need to finish today.'] },
      { cue: 'Тебе не нужно приходить завтра.', models: ["You don't have to come tomorrow.", 'You do not need to come tomorrow.'] },
      { cue: 'Он должен носить форму на работе.', models: ['He has to wear a uniform at work.', 'He has to wear a uniform for work.'] },
      { cue: 'Мне пришлось ждать два часа.', models: ['I had to wait for two hours.', 'I had to wait two hours.'] },
      { cue: 'Нам нужно бронировать заранее?', models: ['Do we have to book in advance?', 'Do we need to book ahead?'] },
      { cue: 'Она не обязана платить сейчас.', models: ["She doesn't have to pay now.", 'She does not need to pay now.'] },
      { cue: 'Мне нужно позвонить врачу.', models: ['I have to call the doctor.', 'I need to phone the doctor.'] },
      { cue: 'Они должны быть там к девяти.', models: ['They have to be there by nine.', 'They need to be there by nine.'] },
    ],
  },
  {
    id: 'must_mustnt', name: 'Обязательно / нельзя', category: 'Модальность', level: 'A2',
    form: 'must / mustn’t + verb', meaning: 'Сильная необходимость или запрет.',
    repair: 'После must/mustn’t используй начальную форму глагола.',
    full: /\b(must|mustn't|must not)\s+[a-z]+\b/, partial: /\b(must|mustn't|must not)\b/,
    drills: [
      { cue: 'Ты обязательно должен увидеть это.', models: ['You must see this.', 'You really must see this.'] },
      { cue: 'Мы должны быть осторожны.', models: ['We must be careful.', 'We really must be careful.'] },
      { cue: 'Здесь нельзя курить.', models: ["You mustn't smoke here.", 'You must not smoke here.'] },
      { cue: 'Я должен не забыть позвонить ей.', models: ['I must remember to call her.', 'I must remember to phone her.'] },
      { cue: 'Ты не должен это трогать.', models: ["You mustn't touch that.", 'You must not touch it.'] },
      { cue: 'Нам нужно сейчас идти.', models: ['We must go now.', 'We really must leave now.'] },
      { cue: 'Водители обязаны остановиться.', models: ['Drivers must stop.', 'Drivers must stop here.'] },
      { cue: 'Ты не должен опаздывать.', models: ["You mustn't be late.", 'You must not arrive late.'] },
      { cue: 'Я обязательно должен закончить это сегодня.', models: ['I must finish this today.', 'I really must get this done today.'] },
      { cue: 'Мы не должны терять время.', models: ["We mustn't waste time.", 'We must not waste any time.'] },
    ],
  },
  {
    id: 'may_might', name: 'Возможно / может быть', category: 'Модальность', level: 'B1',
    form: 'may / might + verb', meaning: 'Неуверенная возможность сейчас или в будущем.',
    repair: 'Для вероятности без уверенности используй may/might + глагол.',
    full: /\b(may|might)\s+(not\s+)?[a-z]+\b/, partial: /\b(may|might)\b/,
    drills: [
      { cue: 'Я, возможно, приду позже.', models: ['I might come later.', 'I may come later.'] },
      { cue: 'Она может быть дома.', models: ['She might be at home.', 'She may be home.'] },
      { cue: 'Сегодня может пойти дождь.', models: ['It might rain today.', 'It may rain later.'] },
      { cue: 'Мы, возможно, останемся ещё на ночь.', models: ['We might stay another night.', 'We may stay one more night.'] },
      { cue: 'Он может не знать об этом.', models: ['He might not know about it.', 'He may not know.'] },
      { cue: 'Я, возможно, куплю новый ноутбук.', models: ['I might buy a new laptop.', 'I may get a new laptop.'] },
      { cue: 'Они могут опоздать.', models: ['They might be late.', 'They may arrive late.'] },
      { cue: 'Это может занять несколько дней.', models: ['It might take a few days.', 'It may take several days.'] },
      { cue: 'Я, возможно, не смогу прийти.', models: ["I might not be able to come.", 'I may not be able to make it.'] },
      { cue: 'Она может передумать.', models: ['She might change her mind.', 'She may change her mind.'] },
    ],
  },
  {
    id: 'should_have', name: 'Надо было сделать', category: 'Модальность', level: 'B1–B2',
    form: 'should have + V3', meaning: 'Правильное действие в прошлом, которое не произошло.',
    repair: 'Оцениваешь прошлое задним числом: should have + V3.',
    full: /\bshould\s+(have|'ve)\b|\bshouldn't\s+(have|'ve)\b/, partial: /\bshould\b|\bshouldn't\b/,
    drills: [
      { cue: 'Надо было зарядить телефон вчера.', models: ['I should have charged my phone yesterday.', "I should've charged it yesterday."] },
      { cue: 'Нам надо было выехать раньше.', models: ['We should have left earlier.', "We should've set off earlier."] },
      { cue: 'Тебе надо было ответить сразу.', models: ['You should have replied straight away.', "You should've answered immediately."] },
      { cue: 'Мне надо было купить билет раньше.', models: ['I should have bought the ticket earlier.', "I should've booked it sooner."] },
      { cue: 'Ей надо было предупредить нас.', models: ['She should have warned us.', "She should've let us know."] },
      { cue: 'Нам не надо было соглашаться так быстро.', models: ["We shouldn't have agreed so quickly.", 'We should not have said yes that fast.'] },
      { cue: 'Мне надо было проверить прогноз.', models: ['I should have checked the forecast.', "I should've looked at the weather first."] },
      { cue: 'Тебе не надо было ему это говорить.', models: ["You shouldn't have told him that.", 'You should not have said that to him.'] },
      { cue: 'Нам надо было взять карту.', models: ['We should have taken a map.', "We should've brought a map with us."] },
      { cue: 'Мне надо было сохранить копию файла.', models: ['I should have saved a copy of the file.', "I should've kept a backup."] },
    ],
  },
  {
    id: 'could_have', name: 'Мог бы, но не сделал', category: 'Модальность', level: 'B1–B2',
    form: 'could have + V3', meaning: 'Нереализованная возможность в прошлом.',
    repair: 'Для возможности, которая была, но не реализовалась: could have + V3.',
    full: /\bcould\s+(have|'ve)\s+[a-z]+\b/, partial: /\bcould\s+(have|'ve)\b/,
    drills: [
      { cue: 'Я мог бы позвонить раньше.', models: ['I could have called earlier.', "I could've phoned earlier."] },
      { cue: 'Мы могли бы взять такси.', models: ['We could have taken a taxi.', "We could've got a taxi."] },
      { cue: 'Ты мог бы предупредить меня.', models: ['You could have warned me.', "You could've let me know."] },
      { cue: 'Она могла бы выбрать другой вариант.', models: ['She could have chosen another option.', "She could've picked something else."] },
      { cue: 'Они могли бы приехать поездом.', models: ['They could have come by train.', "They could've taken the train."] },
      { cue: 'Я мог бы остаться ещё на день.', models: ['I could have stayed another day.', "I could've stayed one more day."] },
      { cue: 'Мы могли бы сэкономить деньги.', models: ['We could have saved money.', "We could've saved some money."] },
      { cue: 'Ты мог бы спросить его напрямую.', models: ['You could have asked him directly.', "You could've asked him yourself."] },
      { cue: 'Она могла бы закончить вчера.', models: ['She could have finished yesterday.', "She could've got it done yesterday."] },
      { cue: 'Я мог бы не покупать новый.', models: ["I could have kept the old one.", "I could've avoided buying a new one."] },
    ],
  },
  {
    id: 'must_have', name: 'Наверняка произошло', category: 'Модальность', level: 'B2',
    form: 'must have + V3', meaning: 'Сильный вывод о прошлом на основе признаков.',
    repair: 'Для уверенного предположения о прошлом: must have + V3.',
    full: /\bmust\s+(have|'ve)\s+[a-z]+\b/, partial: /\bmust\s+(have|'ve)\b/,
    drills: [
      { cue: 'Он, должно быть, забыл о встрече.', models: ['He must have forgotten about the meeting.', "He must've forgotten the meeting."] },
      { cue: 'Она, наверное, уже ушла.', models: ['She must have left already.', "She must've gone already."] },
      { cue: 'Они, должно быть, перепутали адрес.', models: ['They must have got the address wrong.', 'They must have mixed up the address.'] },
      { cue: 'Ты, должно быть, очень устал после дороги.', models: ['You must have been exhausted after the trip.', 'You must have been really tired after travelling.'] },
      { cue: 'Он, наверное, не услышал телефон.', models: ["He must not have heard the phone.", "He must've missed the call."] },
      { cue: 'Мы, должно быть, свернули не туда.', models: ['We must have taken a wrong turn.', "We must've gone the wrong way."] },
      { cue: 'Она, должно быть, работала всю ночь.', models: ['She must have worked all night.', 'She must have been working all night.'] },
      { cue: 'Они, должно быть, уже получили письмо.', models: ['They must have received the email by now.', "They must've got the message already."] },
      { cue: 'Я, должно быть, оставил кошелёк дома.', models: ['I must have left my wallet at home.', "I must've forgotten my wallet at home."] },
      { cue: 'Он, должно быть, понял неправильно.', models: ['He must have misunderstood.', "He must've got the wrong idea."] },
    ],
  },
  {
    id: 'might_as_well', name: 'Раз уж так — можно и…', category: 'Модальность', level: 'B2',
    form: 'might as well + verb', meaning: 'Практичный выбор, когда альтернативы не лучше.',
    repair: 'Когда «раз уж всё равно…»: might as well + глагол.',
    full: /\bmight as well\b/, partial: /\bmight\b.*\bwell\b/,
    drills: [
      { cue: 'Автобус ушёл. Раз уж ждать сорок минут, можно пойти пешком.', models: ['We might as well walk.', 'We might as well go on foot.'] },
      { cue: 'Мы уже здесь. Можно заодно зайти в магазин.', models: ['We might as well go into the shop.', 'We might as well stop by the shop.'] },
      { cue: 'Раз уж всё равно включил компьютер, можно проверить почту.', models: ['I might as well check my email.', 'I might as well have a look at my email.'] },
      { cue: 'Если поезд отменили, можно остаться ещё на ночь.', models: ['We might as well stay another night.', 'We might as well stay here one more night.'] },
      { cue: 'Раз всё равно готовишь, приготовь на двоих.', models: ['You might as well cook for two.', 'You might as well make enough for two.'] },
      { cue: 'Раз уж начали, давай закончим.', models: ['We might as well finish it.', 'We might as well see it through.'] },
      { cue: 'Раз уж дождь не прекращается, можно посмотреть фильм.', models: ['We might as well watch a film.', 'We might as well put a movie on.'] },
      { cue: 'Раз уж он всё равно знает, можно сказать ему правду.', models: ['We might as well tell him the truth.', 'We might as well be honest with him.'] },
      { cue: 'Раз уж приехали рано, можно выпить кофе.', models: ['We might as well get a coffee.', 'We might as well have a coffee.'] },
      { cue: 'Раз уж больше нечего делать, можно начать сейчас.', models: ['We might as well start now.', 'We might as well get started now.'] },
    ],
  },
  {
    id: 'would_rather', name: 'Я бы предпочёл', category: 'Модальность', level: 'B1–B2',
    form: "I'd rather + verb", meaning: 'Предпочтение между вариантами.',
    repair: 'После would rather идёт начальная форма без to.',
    full: /\b(would rather|'d rather)\b/, partial: /\brather\b/,
    drills: [
      { cue: 'Я бы лучше остался дома сегодня.', models: ["I'd rather stay home tonight.", 'I would rather stay in tonight.'] },
      { cue: 'Я бы предпочёл поговорить завтра.', models: ["I'd rather talk tomorrow.", 'I would rather discuss it tomorrow.'] },
      { cue: 'Мы бы лучше поехали поездом.', models: ["We'd rather take the train.", 'We would rather go by train.'] },
      { cue: 'Я бы лучше не обсуждал это сейчас.', models: ["I'd rather not discuss it now.", 'I would rather not talk about it right now.'] },
      { cue: 'Она бы предпочла работать из дома.', models: ["She'd rather work from home.", 'She would rather work at home.'] },
      { cue: 'Я бы лучше заплатил немного больше.', models: ["I'd rather pay a little more.", 'I would rather spend a bit more.'] },
      { cue: 'Мы бы предпочли подождать.', models: ["We'd rather wait.", 'We would rather wait a little longer.'] },
      { cue: 'Он бы лучше поехал один.', models: ["He'd rather go alone.", 'He would rather travel by himself.'] },
      { cue: 'Я бы лучше сделал это сам.', models: ["I'd rather do it myself.", 'I would rather handle it myself.'] },
      { cue: 'Ты бы предпочёл остаться или уйти?', models: ['Would you rather stay or leave?', 'Would you rather stay here or go?'] },
    ],
  },
  {
    id: 'supposed_to', name: 'По идее / по правилам', category: 'Модальность', level: 'B1–B2',
    form: 'be supposed to + verb', meaning: 'План, ожидание, правило или договорённость.',
    repair: 'Для «по идее / согласно плану / по правилам»: be supposed to.',
    full: /\b(am|is|are|was|were|'m|'s|'re)\s+(not\s+)?supposed to\b/, partial: /\bsupposed to\b/,
    drills: [
      { cue: 'Он должен был приехать к шести.', models: ['He was supposed to be here by six.', 'He was supposed to arrive by six.'] },
      { cue: 'Мы должны начать в девять, верно?', models: ["We're supposed to start at nine, right?", 'We are supposed to begin at nine, aren’t we?'] },
      { cue: 'Мы не должны делиться этим файлом.', models: ["We're not supposed to share this file.", 'We are not supposed to send this file outside.'] },
      { cue: 'Поезд по расписанию должен прийти в 18:20.', models: ['The train is supposed to arrive at 6:20.', 'The train is supposed to get in at 6:20.'] },
      { cue: 'Ты должен был позвонить мне вчера.', models: ['You were supposed to call me yesterday.', 'You were supposed to phone me yesterday.'] },
      { cue: 'Эта кнопка должна открыть меню.', models: ['This button is supposed to open the menu.', 'This button is supposed to bring up the menu.'] },
      { cue: 'Нам нельзя парковаться здесь.', models: ["We're not supposed to park here.", 'We are not supposed to leave the car here.'] },
      { cue: 'Встреча должна закончиться к пяти.', models: ['The meeting is supposed to finish by five.', 'The meeting is supposed to be over by five.'] },
      { cue: 'Он должен сейчас быть в отпуске.', models: ["He's supposed to be on holiday now.", 'He is supposed to be on vacation at the moment.'] },
      { cue: 'Что я должен здесь делать?', models: ['What am I supposed to do here?', 'What exactly am I supposed to do?'] },
    ],
  },
]
