import type { Pattern } from './retrievalTypes'

export const CONVERSATION_PATTERNS: Pattern[] = [
  {
    id: 'would_like', name: 'Я бы хотел / хотела', category: 'Разговорные конструкции', level: 'A2',
    form: 'would like + noun / to + verb', meaning: 'Вежливо выразить желание или просьбу.',
    repair: 'Для вежливого «я бы хотел» используй would like.',
    full: /\b(would like|'d like)\b/, partial: /\blike\b/,
    drills: [
      { cue: 'Я бы хотел кофе.', models: ["I'd like a coffee.", 'I would like a coffee, please.'] },
      { cue: 'Я бы хотел забронировать столик.', models: ["I'd like to book a table.", 'I would like to reserve a table.'] },
      { cue: 'Мы бы хотели остаться ещё на ночь.', models: ["We'd like to stay another night.", 'We would like to stay one more night.'] },
      { cue: 'Она хотела бы поговорить с менеджером.', models: ["She'd like to speak to the manager.", 'She would like to talk to the manager.'] },
      { cue: 'Я бы хотел примерить это.', models: ["I'd like to try this on.", 'I would like to try it on.'] },
      { cue: 'Вы бы хотели чай?', models: ['Would you like some tea?', 'Would you like a cup of tea?'] },
      { cue: 'Я бы не хотел опаздывать.', models: ["I wouldn't like to be late.", 'I would rather not be late.'] },
      { cue: 'Мы бы хотели узнать цену.', models: ["We'd like to know the price.", 'We would like to find out how much it costs.'] },
      { cue: 'Я бы хотел поменять номер.', models: ["I'd like to change rooms.", 'I would like a different room.'] },
      { cue: 'Она хотела бы присоединиться к нам.', models: ["She'd like to join us.", 'She would like to come with us.'] },
    ],
  },
  {
    id: 'how_about', name: 'А как насчёт…?', category: 'Разговорные конструкции', level: 'A2',
    form: 'How about + noun / -ing?', meaning: 'Предложить идею или вариант.',
    repair: 'После How about для действия используй -ing.',
    full: /\bhow about\b.*\b[a-z]+ing\b|\bhow about\b/, partial: /\bhow about\b/,
    drills: [
      { cue: 'А как насчёт кофе?', models: ['How about a coffee?', 'How about getting a coffee?'] },
      { cue: 'Может, пойдём пешком?', models: ['How about walking?', 'How about going on foot?'] },
      { cue: 'Как насчёт встретиться завтра?', models: ['How about meeting tomorrow?', 'How about we meet tomorrow?'] },
      { cue: 'Может, посмотрим фильм?', models: ['How about watching a film?', 'How about putting on a movie?'] },
      { cue: 'Как насчёт заказать пиццу?', models: ['How about ordering pizza?', 'How about getting a pizza?'] },
      { cue: 'Может, позвоним ему?', models: ['How about calling him?', 'How about giving him a call?'] },
      { cue: 'Как насчёт другой даты?', models: ['How about another date?', 'How about a different day?'] },
      { cue: 'Может, начнём пораньше?', models: ['How about starting earlier?', 'How about we start a bit earlier?'] },
      { cue: 'Как насчёт поехать поездом?', models: ['How about taking the train?', 'How about going by train?'] },
      { cue: 'Может, сделаем перерыв?', models: ['How about taking a break?', 'How about we have a break?'] },
    ],
  },
  {
    id: 'it_depends_on', name: 'Это зависит от…', category: 'Разговорные конструкции', level: 'A2–B1',
    form: 'It depends on + noun / -ing', meaning: 'Показать, что ответ меняется в зависимости от условия.',
    repair: 'После depends используй on.',
    full: /\bit depends on\b|\bdepends on\b/, partial: /\bdepends\b/,
    drills: [
      { cue: 'Это зависит от погоды.', models: ['It depends on the weather.', 'That depends on the weather.'] },
      { cue: 'Зависит от цены.', models: ['It depends on the price.', 'That depends on how much it costs.'] },
      { cue: 'Это зависит от того, сколько у нас времени.', models: ['It depends on how much time we have.', 'That depends on how much time we have.'] },
      { cue: 'Зависит от того, кто придёт.', models: ['It depends on who comes.', 'That depends on who is coming.'] },
      { cue: 'Это зависит от того, когда ты закончишь.', models: ['It depends on when you finish.', 'That depends on what time you finish.'] },
      { cue: 'Зависит от того, насколько это срочно.', models: ['It depends on how urgent it is.', 'That depends on how quickly you need it.'] },
      { cue: 'Это зависит от трафика.', models: ['It depends on the traffic.', 'That depends on how bad the traffic is.'] },
      { cue: 'Зависит от того, хочешь ли ты ждать.', models: ['It depends on whether you want to wait.', 'That depends on if you are willing to wait.'] },
      { cue: 'Это зависит от результата.', models: ['It depends on the result.', 'That depends on the outcome.'] },
      { cue: 'Зависит от того, как ты на это смотришь.', models: ['It depends on how you look at it.', 'That depends on your point of view.'] },
    ],
  },
  {
    id: 'feel_like', name: 'Хочется / есть настроение', category: 'Разговорные конструкции', level: 'B1',
    form: 'feel like + noun / -ing', meaning: 'Спонтанное желание или настроение что-то сделать.',
    repair: 'После feel like для действия используй -ing.',
    full: /\bfeel(s|ing)? like\b.*\b[a-z]+ing\b|\bfeel like\b/, partial: /\bfeel like\b/,
    drills: [
      { cue: 'Мне хочется кофе.', models: ['I feel like a coffee.', 'I feel like having a coffee.'] },
      { cue: 'Мне хочется прогуляться.', models: ['I feel like going for a walk.', 'I feel like taking a walk.'] },
      { cue: 'Сегодня не хочется готовить.', models: ["I don't feel like cooking today.", 'I do not feel like making dinner today.'] },
      { cue: 'Тебе хочется куда-нибудь выйти?', models: ['Do you feel like going out?', 'Do you feel like going somewhere?'] },
      { cue: 'Мне хочется посмотреть что-нибудь лёгкое.', models: ['I feel like watching something light.', 'I feel like putting on something easy to watch.'] },
      { cue: 'Она не хочет об этом говорить.', models: ["She doesn't feel like talking about it.", 'She does not feel like discussing it.'] },
      { cue: 'Мне хочется остаться дома.', models: ['I feel like staying home.', 'I feel like staying in.'] },
      { cue: 'Нам хочется попробовать новое место.', models: ['We feel like trying a new place.', 'We feel like checking out somewhere new.'] },
      { cue: 'Тебе хочется пиццу?', models: ['Do you feel like pizza?', 'Do you feel like having pizza?'] },
      { cue: 'Мне сегодня ничего не хочется делать.', models: ["I don't feel like doing anything today.", 'I feel like doing absolutely nothing today.'] },
    ],
  },
  {
    id: 'look_forward_to', name: 'Жду с нетерпением', category: 'Разговорные конструкции', level: 'B1',
    form: 'look forward to + noun / -ing', meaning: 'С радостью ждать будущего события.',
    repair: 'В look forward to слово to — предлог, поэтому дальше noun или -ing.',
    full: /\blook(s|ed|ing)? forward to\b.*\b[a-z]+ing\b|\blook forward to\b/, partial: /\bforward to\b/,
    drills: [
      { cue: 'Я очень жду выходных.', models: ["I'm looking forward to the weekend.", 'I am really looking forward to this weekend.'] },
      { cue: 'Я жду встречи с тобой.', models: ["I'm looking forward to seeing you.", 'I look forward to seeing you.'] },
      { cue: 'Мы ждём поездки.', models: ["We're looking forward to the trip.", 'We are really looking forward to travelling.'] },
      { cue: 'Она ждёт начала новой работы.', models: ["She's looking forward to starting her new job.", 'She is looking forward to the new job.'] },
      { cue: 'Я жду возможности попробовать это.', models: ["I'm looking forward to trying it.", 'I am looking forward to giving it a try.'] },
      { cue: 'Они ждут возвращения домой.', models: ["They're looking forward to going home.", 'They are looking forward to getting back home.'] },
      { cue: 'Я не жду этого разговора.', models: ["I'm not looking forward to that conversation.", 'I am not looking forward to having that conversation.'] },
      { cue: 'Мы ждём встречи с командой.', models: ["We're looking forward to meeting the team.", 'We look forward to meeting everyone.'] },
      { cue: 'Она ждёт отпуска.', models: ["She's looking forward to her holiday.", 'She is looking forward to going on holiday.'] },
      { cue: 'Я жду твоего ответа.', models: ['I look forward to hearing from you.', "I'm looking forward to your reply."] },
    ],
  },
  {
    id: 'get_used_to', name: 'Привыкать к новому', category: 'Разговорные конструкции', level: 'B1–B2',
    form: 'get used to + noun / -ing', meaning: 'Постепенно привыкать к ситуации или действию.',
    repair: 'После get used to идёт noun или -ing, потому что to здесь предлог.',
    full: /\b(get|getting|got) used to\b/, partial: /\bused to\b/,
    drills: [
      { cue: 'Я привыкаю вставать раньше.', models: ["I'm getting used to getting up earlier.", 'I am getting used to waking up earlier.'] },
      { cue: 'Она привыкла к шуму.', models: ['She got used to the noise.', 'She has got used to the noise.'] },
      { cue: 'Мы ещё не привыкли к новой системе.', models: ["We haven't got used to the new system yet.", "We're still getting used to the new system."] },
      { cue: 'Ты быстро привыкнешь к погоде.', models: ["You'll get used to the weather quickly.", 'You will soon get used to the weather.'] },
      { cue: 'Мне трудно привыкнуть работать из дома.', models: ["I'm finding it hard to get used to working from home.", 'It is hard for me to get used to working at home.'] },
      { cue: 'Он постепенно привыкает к городу.', models: ["He's getting used to the city.", 'He is slowly getting used to living in the city.'] },
      { cue: 'Я привык к этой клавиатуре.', models: ["I've got used to this keyboard.", 'I am used to this keyboard now.'] },
      { cue: 'Они не привыкли есть так поздно.', models: ["They aren't used to eating this late.", "They haven't got used to eating so late."] },
      { cue: 'Сначала было странно, но я привык.', models: ['It felt strange at first, but I got used to it.', 'It was odd at first, but I got used to it.'] },
      { cue: 'Нужно время, чтобы привыкнуть к новому графику.', models: ['It takes time to get used to the new schedule.', 'You need time to get used to a new routine.'] },
    ],
  },
  {
    id: 'about_to', name: 'Вот-вот собираюсь', category: 'Разговорные конструкции', level: 'B1',
    form: 'be about to + verb', meaning: 'Действие должно произойти буквально сейчас.',
    repair: 'Для «вот-вот / уже собирался»: be about to + глагол.',
    full: /\b(am|is|are|was|were|'m|'s|'re)\s+(just\s+)?about to\b/, partial: /\babout to\b/,
    drills: [
      { cue: 'Я как раз собирался выходить.', models: ['I was just about to leave.', 'I was about to head out.'] },
      { cue: 'Я как раз собирался тебе звонить.', models: ['I was just about to call you.', 'I was about to give you a call.'] },
      { cue: 'Поезд вот-вот отправится.', models: ['The train is about to leave.', 'The train is just about to depart.'] },
      { cue: 'Мы вот-вот начнём.', models: ["We're about to start.", "We're just about to begin."] },
      { cue: 'Фильм вот-вот начнётся.', models: ['The film is about to start.', 'The movie is just about to begin.'] },
      { cue: 'Я уже собирался отправить письмо.', models: ['I was about to send the email.', 'I was just about to send it.'] },
      { cue: 'Она вот-вот расплачется.', models: ["She's about to cry.", "She looks like she's about to cry."] },
      { cue: 'Самолёт вот-вот приземлится.', models: ['The plane is about to land.', 'The plane is just about to touch down.'] },
      { cue: 'Мы уже собирались уходить, когда он пришёл.', models: ['We were about to leave when he arrived.', 'We were just about to go when he turned up.'] },
      { cue: 'Я хотел сказать то же самое.', models: ['I was about to say the same thing.', 'I was just about to say that.'] },
    ],
  },
  {
    id: 'end_up', name: 'В итоге получилось', category: 'Разговорные конструкции', level: 'B1–B2',
    form: 'end up + -ing', meaning: 'Конечный, часто неожиданный результат.',
    repair: 'Для «в итоге» после end up обычно идёт -ing.',
    full: /\b(end|ended|ends|ending)\s+up\s+[a-z]+ing\b/, partial: /\bend(ed|s|ing)?\s+up\b/,
    drills: [
      { cue: 'В итоге я остался там на весь вечер.', models: ['I ended up staying there all evening.', 'I ended up spending the whole evening there.'] },
      { cue: 'В итоге мы поехали поездом.', models: ['We ended up taking the train.', 'We ended up going by train.'] },
      { cue: 'В итоге она купила машину.', models: ['She ended up buying a car.', 'She ended up getting a car.'] },
      { cue: 'В итоге я посмотрел весь сезон.', models: ['I ended up watching the whole season.', 'I ended up binge-watching the whole season.'] },
      { cue: 'В итоге мы потратили гораздо больше.', models: ['We ended up spending much more.', 'We ended up paying a lot more.'] },
      { cue: 'В итоге он работал там десять лет.', models: ['He ended up working there for ten years.', 'He ended up staying with the company for ten years.'] },
      { cue: 'В итоге я сам всё сделал.', models: ['I ended up doing everything myself.', 'I ended up handling it all myself.'] },
      { cue: 'В итоге они отменили поездку.', models: ['They ended up cancelling the trip.', 'They ended up calling the trip off.'] },
      { cue: 'В итоге мы говорили до двух ночи.', models: ['We ended up talking until two in the morning.', 'We ended up chatting until 2 a.m.'] },
      { cue: 'В итоге он согласился.', models: ['He ended up agreeing.', 'He ended up saying yes.'] },
    ],
  },
  {
    id: 'no_point_in', name: 'Нет смысла', category: 'Разговорные конструкции', level: 'B1–B2',
    form: "there's no point in + -ing", meaning: 'Действие бессмысленно или ничего не изменит.',
    repair: 'После no point in используй -ing.',
    full: /\b(no point in|there's no point in|there is no point in)\b.*\b[a-z]+ing\b/, partial: /\bno point\b/,
    drills: [
      { cue: 'Нет смысла спорить об этом сейчас.', models: ["There's no point in arguing about it now.", 'There is no point in discussing it right now.'] },
      { cue: 'Нет смысла ждать ещё час.', models: ["There's no point in waiting another hour.", 'There is no point in staying here for another hour.'] },
      { cue: 'Нет смысла ему звонить — он за рулём.', models: ["There's no point in calling him; he's driving.", 'There is no point in phoning him now.'] },
      { cue: 'Нет смысла покупать новый, если этот работает.', models: ["There's no point in buying a new one if this one works.", 'There is no point in replacing it if it still works.'] },
      { cue: 'Нет смысла волноваться заранее.', models: ["There's no point in worrying in advance.", 'There is no point in worrying about it yet.'] },
      { cue: 'Нет смысла начинать всё сначала.', models: ["There's no point in starting all over again.", 'There is no point in starting from scratch.'] },
      { cue: 'Нет смысла скрывать это от неё.', models: ["There's no point in hiding it from her.", 'There is no point in keeping it from her.'] },
      { cue: 'Нет смысла брать такси — мы почти пришли.', models: ["There's no point in taking a taxi; we're almost there.", 'There is no point in getting a cab now.'] },
      { cue: 'Нет смысла пытаться его переубедить.', models: ["There's no point in trying to change his mind.", 'There is no point in trying to convince him.'] },
      { cue: 'Нет смысла делать это дважды.', models: ["There's no point in doing it twice.", 'There is no point in doing the same thing twice.'] },
    ],
  },
  {
    id: 'managed_to', name: 'Всё-таки удалось', category: 'Разговорные конструкции', level: 'B1–B2',
    form: 'manage to + verb', meaning: 'Удалось сделать что-то несмотря на трудность.',
    repair: 'Когда важны трудность и успешный результат: manage to + глагол.',
    full: /\b(manage|managed|manages)\s+to\b/, partial: /\bmanage(d|s)?\b/,
    drills: [
      { cue: 'Мне всё-таки удалось успеть на поезд.', models: ['I managed to catch the train.', 'I managed to make the train.'] },
      { cue: 'Нам удалось закончить это сегодня.', models: ['We managed to finish it today.', 'We managed to get it done today.'] },
      { cue: 'Ей удалось найти билет на пятницу.', models: ['She managed to find a ticket for Friday.', 'She managed to get a ticket for Friday.'] },
      { cue: 'Мне удалось найти дом без карты.', models: ['I managed to find the house without a map.', 'I managed to get there without a map.'] },
      { cue: 'Он всё-таки смог открыть дверь.', models: ['He managed to open the door.', 'He managed to get the door open.'] },
      { cue: 'Мы смогли договориться о цене.', models: ['We managed to agree on a price.', 'We managed to reach an agreement on the price.'] },
      { cue: 'Мне удалось поспать пару часов.', models: ['I managed to get a couple of hours of sleep.', 'I managed to sleep for a couple of hours.'] },
      { cue: 'Она всё-таки связалась с ним.', models: ['She managed to contact him.', 'She managed to get hold of him.'] },
      { cue: 'Нам удалось избежать пробки.', models: ['We managed to avoid the traffic.', 'We managed to miss the worst of the traffic.'] },
      { cue: 'Я всё-таки починил это сам.', models: ['I managed to fix it myself.', 'I managed to repair it on my own.'] },
    ],
  },
]
