import type { Pattern } from './retrievalTypes'

export const TIMES_PATTERNS: Pattern[] = [
  {
    id: 'present_simple_habit', name: 'Обычно / регулярно', category: 'Времена и aspect', level: 'A2',
    form: 'Present Simple', meaning: 'Привычки, регулярные действия и постоянные факты.',
    repair: 'Для того, что происходит обычно или регулярно, используй Present Simple.',
    full: /\b(i|you|we|they)\s+[a-z]+\b|\b(he|she|it)\s+[a-z]+s\b/, partial: /\b(always|usually|often|every|sometimes|never)\b/,
    drills: [
      { cue: 'Я обычно встаю в семь.', models: ['I usually get up at seven.', 'I normally get up at seven.'] },
      { cue: 'Она работает из дома по пятницам.', models: ['She works from home on Fridays.', 'She works at home on Fridays.'] },
      { cue: 'Мы часто ужинаем поздно.', models: ['We often have dinner late.', 'We often eat dinner late.'] },
      { cue: 'Он каждый день ходит пешком на работу.', models: ['He walks to work every day.', 'He goes to work on foot every day.'] },
      { cue: 'Я не пью кофе вечером.', models: ["I don't drink coffee in the evening.", 'I never drink coffee at night.'] },
      { cue: 'Ты обычно готовишь дома?', models: ['Do you usually cook at home?', 'Do you normally cook at home?'] },
      { cue: 'Автобус приходит каждые десять минут.', models: ['The bus comes every ten minutes.', 'The bus runs every ten minutes.'] },
      { cue: 'Она иногда опаздывает.', models: ['She sometimes arrives late.', 'She is sometimes late.'] },
      { cue: 'Мы не работаем по воскресеньям.', models: ["We don't work on Sundays.", 'We never work on Sundays.'] },
      { cue: 'Магазин закрывается в девять.', models: ['The shop closes at nine.', 'The store closes at nine.'] },
    ],
  },
  {
    id: 'present_continuous_now', name: 'Происходит прямо сейчас', category: 'Времена и aspect', level: 'A2',
    form: 'am/is/are + -ing', meaning: 'Действие происходит сейчас или вокруг настоящего момента.',
    repair: 'Для действия в процессе сейчас: am/is/are + -ing.',
    full: /\b(am|is|are|'m|'s|'re)\s+[a-z]+ing\b/, partial: /\b(now|right now|at the moment)\b/,
    drills: [
      { cue: 'Я сейчас готовлю ужин.', models: ["I'm cooking dinner now.", 'I am making dinner right now.'] },
      { cue: 'Она разговаривает по телефону.', models: ["She's talking on the phone.", 'She is speaking on the phone.'] },
      { cue: 'Мы ждём автобус.', models: ["We're waiting for the bus.", 'We are waiting for our bus.'] },
      { cue: 'Он сейчас работает над новым проектом.', models: ["He's working on a new project.", 'He is working on a new project at the moment.'] },
      { cue: 'Они смотрят фильм.', models: ["They're watching a film.", 'They are watching a movie.'] },
      { cue: 'Ты меня слушаешь?', models: ['Are you listening to me?', 'Are you listening?'] },
      { cue: 'Я сейчас не работаю.', models: ["I'm not working right now.", 'I am not working at the moment.'] },
      { cue: 'Дети играют на улице.', models: ['The children are playing outside.', 'The kids are playing outside.'] },
      { cue: 'Погода становится лучше.', models: ["The weather is getting better.", 'The weather is improving.'] },
      { cue: 'Мы ищем новое жильё.', models: ["We're looking for a new place to live.", 'We are looking for a new flat.'] },
    ],
  },
  {
    id: 'past_simple', name: 'Завершённое прошлое', category: 'Времена и aspect', level: 'A2',
    form: 'Past Simple', meaning: 'Завершённое действие в конкретный момент прошлого.',
    repair: 'Если действие закончилось в прошлом, используй Past Simple.',
    full: /\b(was|were|did|went|had|got|came|saw|made|took|bought|left|called|worked|watched|finished|started|stayed)\b/, partial: /\b(yesterday|last|ago)\b/,
    drills: [
      { cue: 'Я видел его вчера.', models: ['I saw him yesterday.', 'I saw him yesterday afternoon.'] },
      { cue: 'Мы приехали домой поздно.', models: ['We got home late.', 'We arrived home late.'] },
      { cue: 'Она купила новый телефон на прошлой неделе.', models: ['She bought a new phone last week.', 'She got a new phone last week.'] },
      { cue: 'Я позвонил тебе утром.', models: ['I called you this morning.', 'I phoned you this morning.'] },
      { cue: 'Они не пришли на встречу.', models: ["They didn't come to the meeting.", 'They did not show up for the meeting.'] },
      { cue: 'Ты смотрел этот фильм вчера?', models: ['Did you watch that film yesterday?', 'Did you see that movie yesterday?'] },
      { cue: 'Мы жили там три года.', models: ['We lived there for three years.', 'We stayed there for three years.'] },
      { cue: 'Он закончил работу в шесть.', models: ['He finished work at six.', 'He finished working at six.'] },
      { cue: 'Я оставил ключи дома.', models: ['I left my keys at home.', 'I forgot my keys at home.'] },
      { cue: 'Она начала учить английский два года назад.', models: ['She started learning English two years ago.', 'She began studying English two years ago.'] },
    ],
  },
  {
    id: 'past_continuous_interrupted', name: 'Был в процессе, когда…', category: 'Времена и aspect', level: 'A2–B1',
    form: 'was/were + -ing … when + Past Simple', meaning: 'Действие шло, когда произошло другое событие.',
    repair: 'Фон: was/were + -ing. Короткое событие: Past Simple.',
    full: /\b(was|were)\s+[a-z]+ing\b.*\bwhen\b|\bwhen\b.*\b(was|were)\s+[a-z]+ing\b/, partial: /\b(was|were)\s+[a-z]+ing\b/,
    drills: [
      { cue: 'Я ужинал, когда ты позвонил.', models: ['I was having dinner when you called.', 'I was eating dinner when you phoned.'] },
      { cue: 'Мы ехали домой, когда начался дождь.', models: ['We were driving home when it started to rain.', 'We were going home when the rain started.'] },
      { cue: 'Она спала, когда пришло сообщение.', models: ['She was sleeping when the message arrived.', 'She was asleep when the message came in.'] },
      { cue: 'Я принимал душ, когда выключили свет.', models: ['I was having a shower when the lights went out.', 'I was showering when the power went out.'] },
      { cue: 'Они разговаривали, когда вошёл начальник.', models: ['They were talking when the boss came in.', 'They were chatting when the manager walked in.'] },
      { cue: 'Что ты делал, когда я написал?', models: ['What were you doing when I texted you?', 'What were you doing when I sent you a message?'] },
      { cue: 'Я работал, когда услышал шум.', models: ['I was working when I heard the noise.', 'I was working when I heard a sound.'] },
      { cue: 'Мы смотрели телевизор, когда он пришёл.', models: ['We were watching TV when he arrived.', 'We were watching television when he came in.'] },
      { cue: 'Она готовила, когда дети вернулись.', models: ['She was cooking when the children came back.', 'She was making dinner when the kids got home.'] },
      { cue: 'Я шёл по улице, когда увидел её.', models: ['I was walking down the street when I saw her.', 'I was walking outside when I spotted her.'] },
    ],
  },
  {
    id: 'present_perfect_experience', name: 'Опыт к настоящему моменту', category: 'Времена и aspect', level: 'B1',
    form: 'have/has + V3', meaning: 'Опыт или результат к настоящему моменту без конкретного прошлого времени.',
    repair: 'Когда важен опыт к настоящему моменту, а не дата: have/has + V3.',
    full: /\b(have|has|'ve|'s)\s+(ever\s+|never\s+|already\s+|just\s+)?[a-z]+(ed|en|n)\b/, partial: /\b(ever|never|already|yet|just)\b/,
    drills: [
      { cue: 'Я уже был в Лондоне.', models: ["I've already been to London.", 'I have been to London before.'] },
      { cue: 'Ты когда-нибудь пробовал тайскую еду?', models: ['Have you ever tried Thai food?', 'Have you ever had Thai food?'] },
      { cue: 'Она ещё не закончила.', models: ["She hasn't finished yet.", 'She has not finished yet.'] },
      { cue: 'Мы только что приехали.', models: ["We've just arrived.", 'We have just got here.'] },
      { cue: 'Я никогда не летал бизнес-классом.', models: ["I've never flown business class.", 'I have never travelled in business class.'] },
      { cue: 'Он уже видел этот фильм.', models: ["He's already seen this film.", 'He has seen this movie already.'] },
      { cue: 'Ты уже сделал это?', models: ['Have you done it yet?', 'Have you finished it yet?'] },
      { cue: 'Мы несколько раз встречались.', models: ["We've met several times.", 'We have met a few times.'] },
      { cue: 'Я потерял ключи.', models: ["I've lost my keys.", 'I have lost my keys.'] },
      { cue: 'Она никогда раньше этого не делала.', models: ["She's never done this before.", 'She has never tried this before.'] },
    ],
  },
  {
    id: 'future_time_clause', name: 'Когда это случится…', category: 'Времена и aspect', level: 'B1',
    form: 'when/after/before/as soon as + Present Simple, will + verb', meaning: 'Будущее после when/after/before выражается Present Simple, не will.',
    repair: 'После when/after/before/as soon as для будущего используй Present Simple.',
    full: /\b(when|after|before|as soon as)\b[^.?!]*\b(am|is|are|finish|finishes|get|gets|arrive|arrives|come|comes|leave|leaves)\b[^.?!]*\bwill|'ll\b/, partial: /\b(when|after|before|as soon as)\b/,
    drills: [
      { cue: 'Я позвоню тебе, когда приеду.', models: ["I'll call you when I arrive.", 'I will call you when I get there.'] },
      { cue: 'Мы поедим после того, как он придёт.', models: ["We'll eat after he arrives.", 'We will eat after he gets here.'] },
      { cue: 'Я напишу, как только закончу.', models: ["I'll text you as soon as I finish.", 'I will message you as soon as I am done.'] },
      { cue: 'Проверь всё перед тем, как уйдёшь.', models: ['Check everything before you leave.', 'Make sure everything is okay before you go.'] },
      { cue: 'Мы начнём, когда все будут здесь.', models: ["We'll start when everyone is here.", 'We will begin when everybody arrives.'] },
      { cue: 'Я расскажу ему, когда увижу его.', models: ["I'll tell him when I see him.", 'I will let him know when I see him.'] },
      { cue: 'Она позвонит после того, как закончит работу.', models: ["She'll call after she finishes work.", 'She will call when she is done with work.'] },
      { cue: 'Когда погода улучшится, пойдём гулять.', models: ["We'll go for a walk when the weather gets better.", 'We will go out when the weather improves.'] },
      { cue: 'Я отправлю файл, как только получу его.', models: ["I'll send the file as soon as I get it.", 'I will forward the file as soon as I receive it.'] },
      { cue: 'Мы обсудим это после того, как ты вернёшься.', models: ["We'll discuss it after you come back.", 'We will talk about it when you return.'] },
    ],
  },
  {
    id: 'used_to', name: 'Раньше было регулярно', category: 'Времена и aspect', level: 'B1',
    form: 'used to + verb', meaning: 'Прошлая привычка или состояние, которых сейчас уже нет.',
    repair: 'Регулярное прошлое, которое изменилось: used to + начальная форма.',
    full: /\bused to\b|\bdidn't use to\b|\bdid you use to\b/, partial: /\bused\b|\buse to\b/,
    drills: [
      { cue: 'Я раньше курил.', models: ['I used to smoke.', 'I used to be a smoker.'] },
      { cue: 'Они раньше жили у моря.', models: ['They used to live by the sea.', 'They used to live near the coast.'] },
      { cue: 'Я раньше ездил на работу на велосипеде.', models: ['I used to cycle to work.', 'I used to ride my bike to work.'] },
      { cue: 'Здесь раньше был кинотеатр.', models: ['There used to be a cinema here.', 'There used to be a movie theatre here.'] },
      { cue: 'Мы раньше часто встречались по пятницам.', models: ['We used to meet on Fridays.', 'We used to get together every Friday.'] },
      { cue: 'Она раньше боялась летать.', models: ['She used to be afraid of flying.', 'She used to hate flying.'] },
      { cue: 'Я раньше работал по ночам.', models: ['I used to work nights.', 'I used to work at night.'] },
      { cue: 'Он раньше носил очки.', models: ['He used to wear glasses.', 'He used to have to wear glasses.'] },
      { cue: 'Мы раньше не заказывали еду домой.', models: ["We didn't use to order food in.", "We didn't use to get food delivered."] },
      { cue: 'Ты раньше часто сюда приходил?', models: ['Did you use to come here often?', 'Did you use to come here a lot?'] },
    ],
  },
  {
    id: 'present_perfect_continuous', name: 'Длится до настоящего момента', category: 'Времена и aspect', level: 'B1–B2',
    form: 'have/has been + -ing', meaning: 'Процесс начался раньше и продолжается до сейчас или только что закончился.',
    repair: 'Если важен продолжающийся процесс до настоящего момента: have/has been + -ing.',
    full: /\b(have|has|'ve|'s)\s+been\s+[a-z]+ing\b/, partial: /\bbeen\s+[a-z]+ing\b/,
    drills: [
      { cue: 'Я работаю над этим отчётом с восьми утра.', models: ["I've been working on this report since eight.", 'I have been working on this report since 8 a.m.'] },
      { cue: 'Дождь идёт уже три часа.', models: ["It's been raining for three hours.", 'It has been raining for the last three hours.'] },
      { cue: 'Я учу французский последние полгода.', models: ["I've been learning French for the last six months.", 'I have been studying French for six months.'] },
      { cue: 'Она ждёт врача уже сорок минут.', models: ["She's been waiting for the doctor for forty minutes.", 'She has been waiting for forty minutes.'] },
      { cue: 'Мы обсуждаем это с самого утра.', models: ["We've been discussing this all morning.", 'We have been talking about this since this morning.'] },
      { cue: 'Он весь день пытается тебе дозвониться.', models: ["He's been trying to call you all day.", 'He has been trying to reach you all day.'] },
      { cue: 'Я ищу ключи уже двадцать минут.', models: ["I've been looking for my keys for twenty minutes.", 'I have been searching for my keys for twenty minutes.'] },
      { cue: 'Они строят этот дом уже два года.', models: ["They've been building this house for two years.", 'They have been working on this house for two years.'] },
      { cue: 'Ты слишком долго сидишь за компьютером.', models: ["You've been sitting at the computer for too long.", 'You have been working at the computer too long.'] },
      { cue: 'Мы пытаемся решить эту проблему уже несколько недель.', models: ["We've been trying to solve this problem for weeks.", 'We have been working on this problem for several weeks.'] },
    ],
  },
  {
    id: 'wish_past', name: 'Сожаление о прошлом', category: 'Времена и aspect', level: 'B1–B2',
    form: 'wish + had + V3', meaning: 'Сожаление о прошлом действии или решении.',
    repair: 'После wish отодвинь прошлое ещё на шаг назад: had + V3.',
    full: /\bwish\b.*\b(had|hadn't|had not|'d)\b/, partial: /\bwish\b/,
    drills: [
      { cue: 'Жаль, что я тогда не принял ту работу.', models: ["I wish I'd taken that job.", 'I wish I had accepted that job.'] },
      { cue: 'Жаль, что я вчера не лёг раньше.', models: ["I wish I'd gone to bed earlier.", 'I wish I had gone to bed earlier.'] },
      { cue: 'Жаль, что мы купили более дешёвый вариант.', models: ["I wish we hadn't bought the cheaper one.", "I wish we'd bought the better one."] },
      { cue: 'Жаль, что я не забронировал столик заранее.', models: ["I wish I'd booked in advance.", "I wish I'd made a reservation earlier."] },
      { cue: 'Жаль, что я ей тогда не позвонил.', models: ["I wish I'd called her then.", 'I wish I had phoned her.'] },
      { cue: 'Жаль, что я это сказал.', models: ["I wish I hadn't said that.", "I wish I'd kept quiet."] },
      { cue: 'Жаль, что мы не взяли такси.', models: ["I wish we'd taken a taxi.", "I wish we hadn't walked all the way."] },
      { cue: 'Жаль, что я продал старую машину.', models: ["I wish I hadn't sold my old car.", "I wish I'd kept my old car."] },
      { cue: 'Жаль, что я не учил французский раньше.', models: ["I wish I'd learned French earlier.", "I wish I'd studied French at school."] },
      { cue: 'Жаль, что я не перепроверил адрес.', models: ["I wish I'd checked the address.", 'I wish I had double-checked the address.'] },
    ],
  },
  {
    id: 'mixed_conditional', name: 'Прошлое → результат сейчас', category: 'Времена и aspect', level: 'B2',
    form: 'If + had + V3, would/could + V now', meaning: 'Нереальная причина в прошлом и её результат сейчас.',
    repair: 'Причина была в прошлом: if + past perfect. Результат относится к сейчас: would/could + глагол.',
    full: /\bif\b.*\b(had|hadn't|had not|'d)\b.*\b(would|wouldn't|would not|could|'d)\b/, partial: /\bif\b.*\b(would|could)\b/,
    drills: [
      { cue: 'Если бы я лёг раньше, я бы сейчас не был таким уставшим.', models: ["If I'd gone to bed earlier, I wouldn't be so tired now.", 'If I had gone to bed earlier, I would feel better now.'] },
      { cue: 'Если бы она учила французский, она могла бы сейчас говорить с клиентом.', models: ["If she'd learned French, she could talk to the client now.", 'If she had studied French, she could speak to the client now.'] },
      { cue: 'Если бы я принял ту работу, я бы сейчас здесь не работал.', models: ["If I'd taken that job, I wouldn't be working here now.", 'If I had accepted that job, I would not be here now.'] },
      { cue: 'Если бы мы купили новую машину, мы бы сейчас не ремонтировали эту каждую неделю.', models: ["If we'd bought a new car, we wouldn't be fixing this one every week now.", 'If we had bought a new car, we would not have this problem now.'] },
      { cue: 'Если бы он сохранил деньги, ему бы сейчас не пришлось брать кредит.', models: ["If he'd saved the money, he wouldn't need a loan now.", 'If he had saved more, he would not have to borrow money now.'] },
      { cue: 'Если бы я не пропустил поезд, я бы сейчас уже был дома.', models: ["If I hadn't missed the train, I'd be home by now.", 'If I had caught the train, I would be home now.'] },
      { cue: 'Если бы мы переехали тогда, дети сейчас ходили бы в другую школу.', models: ["If we'd moved then, the kids would be at a different school now.", 'If we had moved, the children would go to another school now.'] },
      { cue: 'Если бы она послушала врача, ей бы сейчас было лучше.', models: ["If she'd listened to the doctor, she'd feel better now.", 'If she had followed the doctor’s advice, she would be better now.'] },
      { cue: 'Если бы я не потратил всё, у меня сейчас были бы деньги на поездку.', models: ["If I hadn't spent it all, I'd have money for the trip now.", 'If I had saved some of it, I could afford the trip now.'] },
      { cue: 'Если бы мы начали раньше, сейчас бы не спешили.', models: ["If we'd started earlier, we wouldn't be rushing now.", 'If we had begun earlier, we would not be in a hurry now.'] },
    ],
  },
]
