'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { V2_PATTERNS } from './catalog'
import type { Drill, EvalOutcome, Pattern, Progress } from './types'

type Event = {
  patternId:string; drillId:string; phase:string; transcript:string; firstAttempt:boolean; hintLevel:number;
  meaningScore:0|1|2; targetScore:0|1|2; outcome:EvalOutcome; latencyMs:number; independent:boolean
}
type ProgressMap = Record<string,Progress>
type Turn = { pattern:Pattern; drill?:Drill; free?:boolean; interleaved?:boolean }
type SpeechRecognitionLike={lang:string;interimResults:boolean;continuous:boolean;maxAlternatives:number;start:()=>void;stop:()=>void;abort:()=>void;onstart:(()=>void)|null;onspeechstart:(()=>void)|null;onresult:((e:{results:ArrayLike<{0?:{transcript?:string}}>})=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null}

const C={navy:'#0f1b3d',amber:'#f59e0b',pale:'#fff8ed',ink:'#17213f',muted:'#667085',green:'#15803d',red:'#b42318',line:'#eadfce',blue:'#2563eb'}
const PK='ef_retrieval_v2_progress'; const SK='ef_retrieval_v2_resume'

function n(s:string){return s.toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9' ]+/g,' ').replace(/\s+/g,' ').trim()}
function meaning(d:Drill,raw:string):0|1|2{const t=n(raw);const hits=d.meaningGroups.filter(g=>g.some(x=>x.split('|').some(p=>t.includes(n(p))))).length;const r=hits/Math.max(1,d.meaningGroups.length);return r>=.72?2:r>=.34?1:0}
function evalAnswer(p:Pattern,d:Drill,text:string,first:boolean,hint:number,latency:number):Event{
  const t=n(text); const target:0|1|2=p.targetFull.test(t)?2:p.targetPartial.test(t)?1:0; const m=meaning(d,text); let outcome:EvalOutcome
  if(m===2&&target===2) outcome=first&&hint===0?'TARGET_INDEPENDENT':'TARGET_SUPPORTED'
  else if(m===2) outcome='MEANING_ALTERNATIVE'
  else if(m===1) outcome='MEANING_PARTIAL'
  else if(target>0) outcome='TARGET_NEEDS_REPAIR'
  else outcome='MEANING_MISS'
  return{patternId:p.id,drillId:d.id,phase:d.phase,transcript:text,firstAttempt:first,hintLevel:hint,meaningScore:m,targetScore:target,outcome,latencyMs:latency,independent:outcome==='TARGET_INDEPENDENT'}
}
function copy(e:Event){switch(e.outcome){case'TARGET_INDEPENDENT':return['Смысл и нужная форма получились','Это самостоятельное извлечение без подсказки.',C.green];case'TARGET_SUPPORTED':return['Получилось с поддержкой','Это полезная практика, но не evidence самостоятельного retrieval.',C.blue];case'MEANING_ALTERNATIVE':return['Смысл передан естественно','Но сейчас мы тренируем другой способ выразить эту мысль.',C.amber];case'MEANING_PARTIAL':return['Смысл передан частично','Уточним смысл и дадим минимальную подсказку.',C.amber];case'TARGET_NEEDS_REPAIR':return['Форма появилась, но смысл съехал','Нужно сохранить target и поправить содержание.',C.amber];default:return['Пока не получилось','Сначала поправим смысл, не показывая готовый ответ.',C.red]}}

export default function ExperimentalLab(){
  const[view,setView]=useState<'library'|'practice'|'result'>('library'); const[patternId,setPatternId]=useState(V2_PATTERNS[0].id); const[review,setReview]=useState(false)
  const[turnIndex,setTurnIndex]=useState(0); const[events,setEvents]=useState<Event[]>([]); const[progress,setProgress]=useState<ProgressMap>({}); const[retry,setRetry]=useState(0); const[hint,setHint]=useState(0); const[awaiting,setAwaiting]=useState(true)
  const[typed,setTyped]=useState(''); const[showTyped,setShowTyped]=useState(false); const[recording,setRecording]=useState(false); const[error,setError]=useState('')
  const shown=useRef(Date.now()); const speech=useRef<number|null>(null); const rec=useRef<SpeechRecognitionLike|null>(null)

  useEffect(()=>{try{const p=localStorage.getItem(PK);if(p)setProgress(JSON.parse(p));const s=localStorage.getItem(SK);if(s){const x=JSON.parse(s);if(x?.patternId&&V2_PATTERNS.some(p=>p.id===x.patternId)){setPatternId(x.patternId);setTurnIndex(x.turnIndex||0);setEvents(x.events||[]);setReview(!!x.review)}}}catch{}},[])
  useEffect(()=>{shown.current=Date.now();speech.current=null;setTyped('');setShowTyped(false);setError('');try{rec.current?.abort()}catch{};rec.current=null;setRecording(false)},[turnIndex,retry,view])

  const focus=useMemo(()=>V2_PATTERNS.find(p=>p.id===patternId)!,[patternId])
  const oldPattern=useMemo(()=>{const id=Object.keys(progress).find(id=>id!==patternId);return id?V2_PATTERNS.find(p=>p.id===id)||null:null},[progress,patternId])
  const turns=useMemo<Turn[]>(()=>{const ds=review?focus.drills.filter(d=>['contrast','transfer','delayed'].includes(d.phase)):focus.drills;const list:Turn[]=ds.map(drill=>({pattern:focus,drill}));if(!review&&oldPattern){const od=oldPattern.drills.find(d=>d.phase==='delayed')||oldPattern.drills[oldPattern.drills.length-1];list.splice(Math.min(4,list.length),0,{pattern:oldPattern,drill:od,interleaved:true})}if(!review)list.push({pattern:focus,free:true});return list},[focus,oldPattern,review])
  const turn=turns[turnIndex]; const drill=turn?.drill; const currentEvents=drill?events.filter(e=>e.patternId===turn.pattern.id&&e.drillId===drill.id):events.filter(e=>e.patternId===turn?.pattern.id&&e.drillId==='free'); const last=currentEvents[currentEvents.length-1]

  useEffect(()=>{if(view==='practice')try{localStorage.setItem(SK,JSON.stringify({patternId,turnIndex,events,review}))}catch{}},[view,patternId,turnIndex,events,review])
  function persist(p:ProgressMap){setProgress(p);try{localStorage.setItem(PK,JSON.stringify(p))}catch{}}
  function start(id:string){const pr=progress[id];const due=!!pr&&new Date(pr.nextDueAt).getTime()<=Date.now();setPatternId(id);setReview(due);setTurnIndex(0);setEvents([]);setRetry(0);setHint(0);setAwaiting(true);setView('practice')}
  function recommended(){const due=V2_PATTERNS.find(p=>progress[p.id]&&new Date(progress[p.id].nextDueAt).getTime()<=Date.now());start((due||V2_PATTERNS.find(p=>!progress[p.id])||V2_PATTERNS[0]).id)}
  function next(){if(turnIndex<turns.length-1){setTurnIndex(i=>i+1);setRetry(0);setHint(0);setAwaiting(true)}else finish()}
  function retryNow(){setRetry(r=>r+1);setHint(h=>Math.min(2,h+1));setAwaiting(true)}
  function finish(){const xs=events.filter(e=>e.patternId===patternId);const delayed=xs.filter(e=>e.phase==='delayed').slice(-1)[0];const pass=delayed?.outcome==='TARGET_INDEPENDENT';const old=progress[patternId];const successes=(old?.delayedSuccesses||0)+(pass?1:0);const days=!pass?1:successes<=1?1:successes===2?3:successes===3?7:successes===4?14:30;const nextP={...progress,[patternId]:{sessions:(old?.sessions||0)+1,nextDueAt:new Date(Date.now()+days*86400000).toISOString(),delayedSuccesses:successes,lastOutcome:(xs[xs.length-1]?.outcome||null),lastValidProbeAt:xs.some(e=>e.independent)?new Date().toISOString():(old?.lastValidProbeAt||null)}};persist(nextP);try{localStorage.removeItem(SK)}catch{};setView('result')}

  function submit(text:string,latency:number){if(!turn)return;if(turn.free){const t=n(text);const ts:0|1|2=turn.pattern.targetFull.test(t)?2:turn.pattern.targetPartial.test(t)?1:0;setEvents(x=>[...x,{patternId:turn.pattern.id,drillId:'free',phase:'free',transcript:text,firstAttempt:true,hintLevel:0,meaningScore:2,targetScore:ts,outcome:ts===2?'TARGET_INDEPENDENT':'MEANING_ALTERNATIVE',latencyMs:latency,independent:ts===2}]);setAwaiting(false);return}if(!drill)return;setEvents(x=>[...x,evalAnswer(turn.pattern,drill,text,retry===0,hint,latency)]);setAwaiting(false)}
  function submitTyped(){const t=typed.trim();if(t)submit(t,Math.max(0,Date.now()-shown.current))}
  function voice(){setError('');const w=window as typeof window&{SpeechRecognition?:new()=>SpeechRecognitionLike;webkitSpeechRecognition?:new()=>SpeechRecognitionLike};const SR=w.SpeechRecognition||w.webkitSpeechRecognition;if(!SR){setShowTyped(true);setError('Голосовой ввод здесь не поддерживается. Используй текст.');return}try{const r=new SR();rec.current=r;r.lang='en-US';r.interimResults=false;r.continuous=false;r.maxAlternatives=1;r.onstart=()=>setRecording(true);r.onspeechstart=()=>{speech.current=Date.now()};r.onresult=e=>{const a=e.results[e.results.length-1];const t=a?.[0]?.transcript?.trim();setRecording(false);if(t)submit(t,Math.max(0,(speech.current||Date.now())-shown.current));else setError('Не расслышал. Попробуй ещё раз.')};r.onerror=()=>{setRecording(false);setShowTyped(true);setError('Голосовой ввод не сработал. Используй текст.')};r.onend=()=>setRecording(false);r.start()}catch{setShowTyped(true);setError('Не удалось запустить микрофон.')}}
  function stop(){try{rec.current?.stop()}catch{};setRecording(false)}

  if(view==='library'){const due=V2_PATTERNS.filter(p=>progress[p.id]&&new Date(progress[p.id].nextDueAt).getTime()<=Date.now()).length;return <main style={page}><div style={shell}><p style={kicker}>Everyday Fluency · Retrieval Lab V2</p><h1 style={hero}>Смысл → выбор формы → self-repair → transfer.</h1><p style={lead}>Новый эксперимент после независимого аудита. Здесь target заранее не переводится с русского: сначала живая ситуация, затем минимальная подсказка и повторная попытка. Успех с подсказкой не считается самостоятельным retrieval.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:20}}><button onClick={recommended} style={primary}>Начать рекомендуемую →</button></div><p style={{fontSize:13,color:C.muted}}>На повтор сегодня: {due}. Due skills идут раньше новых.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12,marginTop:24}}>{V2_PATTERNS.map(p=>{const pr=progress[p.id];const isDue=pr&&new Date(pr.nextDueAt).getTime()<=Date.now();return <button key={p.id} onClick={()=>start(p.id)} style={patternCard}><div style={{display:'flex',justifyContent:'space-between'}}><span style={chip}>{isDue?'Повторить сегодня':pr?`Проверка ${new Date(pr.nextDueAt).toLocaleDateString('ru-RU')}`:'Новый'}</span><span style={{fontSize:12,color:C.muted}}>{p.level}</span></div><strong style={{display:'block',marginTop:12,fontSize:18,color:C.navy}}>{p.name}</strong><span style={{display:'block',marginTop:6,fontSize:13,color:C.muted,lineHeight:1.5}}>{p.meaning}</span><code style={{display:'block',marginTop:10,fontSize:12}}>{p.form}</code></button>})}</div></div></main>}

  if(view==='result'){const xs=events.filter(e=>e.patternId===patternId);const first=xs.filter(e=>e.firstAttempt&&e.phase!=='free');const meaningOK=first.filter(e=>e.meaningScore===2).length;const targetOK=first.filter(e=>e.outcome==='TARGET_INDEPENDENT').length;const delayed=xs.filter(e=>e.phase==='delayed').slice(-1)[0];const supported=xs.filter(e=>e.outcome==='TARGET_SUPPORTED').length;const free=xs.find(e=>e.phase==='free');const pr=progress[patternId];return <main style={{...page,background:C.navy,color:'white'}}><div style={shell}><p style={{...kicker,color:'#fbbf24'}}>V2 · {focus.name}</p><h1 style={{...hero,color:'white'}}>Что действительно получилось без подсказки?</h1><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginTop:22}}><div style={result}><small>Смысл с первой попытки</small><strong>{meaningOK}/{first.length}</strong><span>мысль соответствовала ситуации</span></div><div style={result}><small>Нужная форма сама</small><strong>{targetOK}/{first.length}</strong><span>без подсказки и без показанной модели</span></div><div style={result}><small>Delayed-in-session probe</small><strong>{delayed?.outcome==='TARGET_INDEPENDENT'?'Получился':'Не подтверждён'}</strong><span>самый важный сигнал внутри этой сессии</span></div><div style={result}><small>Supported successes</small><strong>{supported}</strong><span>полезная практика, но не mastery evidence</span></div></div>{free&&<div style={summary}><strong>Свободная речь</strong><p style={{margin:'8px 0 0',color:'#cbd5e1'}}>{free.targetScore===2?'Target появился спонтанно.':'Target не появился — и это не ошибка: в free task он не обязателен.'}</p></div>}<div style={summary}><strong>Сохранение навыка ещё не доказано.</strong><p style={{margin:'8px 0 0',color:'#cbd5e1'}}>Следующая короткая проверка: {pr?new Date(pr.nextDueAt).toLocaleDateString('ru-RU'):'—'}. Только delayed success расширяет интервал.</p></div><button onClick={()=>setView('library')} style={{...primary,marginTop:20}}>Закончить</button></div></main>}

  if(!turn)return null; const cp=last?copy(last):null; const success=!!last&&(last.outcome==='TARGET_INDEPENDENT'||last.outcome==='TARGET_SUPPORTED'); const canRetry=!!last&&!success&&retry<2; const reveal=!!last&&!success&&retry>=2; const phase=turn.interleaved?'Interleaving · старый навык':turn.free?'Free production · target не обязателен':review?'Короткий delayed review':drill?.phase==='cold'?'Cold probe · target скрыт':drill?.phase==='runway'?'Blocked runway':drill?.phase==='contrast'?'Contrast boundary':drill?.phase==='transfer'?'Near transfer':drill?.phase==='delayed'?'Delayed-in-session probe':'Varied retrieval'
  return <main style={page}><div style={shell}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><button onClick={()=>setView('library')} style={ghost}>← Библиотека</button><div style={{textAlign:'right'}}><b>{turn.pattern.name}</b><div style={{fontSize:12,color:C.muted}}>{turnIndex+1}/{turns.length}</div></div></div><div style={{height:5,background:'#eadfce',borderRadius:99,overflow:'hidden',marginTop:18}}><div style={{height:'100%',width:`${((turnIndex+1)/turns.length)*100}%`,background:C.amber}}/></div><p style={{...kicker,marginTop:26}}>{phase}</p>{turn.free?<><h1 style={{...hero,fontSize:'clamp(28px,6vw,44px)'}}>{turn.pattern.freePrompt}</h1><div style={notice}>Говори естественно. Target не обязателен — мы только наблюдаем, появится ли он сам.</div></>:<><p style={{fontSize:16,color:C.muted,lineHeight:1.55,marginTop:18}}>{drill?.scenario}</p><h1 style={{...hero,fontSize:'clamp(28px,6vw,44px)'}}>{drill?.prompt}</h1></>}

  {awaiting&&hint>0&&drill&&<div style={hintBox}><div style={small}>Подсказка {hint}/2</div><p style={{margin:'7px 0 0'}}>{hint===1?(currentEvents[currentEvents.length-1]?.meaningScore===2?turn.pattern.starterHint:drill.meaningHint):turn.pattern.formHint}</p>{hint===2&&<code style={{display:'block',marginTop:8,fontWeight:800}}>{turn.pattern.form}</code>}</div>}
  {awaiting&&<section style={{marginTop:24}}><button onClick={recording?stop:voice} style={{...primary,background:recording?'#dc2626':C.navy,color:'white',minWidth:220}}>{recording?'■ Остановить':'🎙 Ответить голосом'}</button>{!recording&&<button onClick={()=>setShowTyped(v=>!v)} style={{...ghost,marginLeft:10}}>{showTyped?'Скрыть текст':'Или напечатать'}</button>}{showTyped&&<div style={{marginTop:12}}><textarea rows={4} value={typed} onChange={e=>setTyped(e.target.value)} placeholder="Your answer in English…" style={textarea}/><button onClick={submitTyped} disabled={!typed.trim()} style={{...primary,marginTop:9}}>Проверить</button></div>}{error&&<p style={{color:C.red}}>{error}</p>}</section>}
  {!awaiting&&last&&cp&&<section style={{marginTop:24}}><div style={quote}><div style={small}>Ты сказал</div><p style={{fontSize:19,margin:'7px 0 0'}}>“{last.transcript}”</p></div><div style={{...card,borderLeft:`5px solid ${cp[2]}`}}><strong>{cp[0]}</strong><p style={{margin:'8px 0 0',color:C.muted}}>{cp[1]}</p><p style={{fontSize:13,color:C.muted}}>Смысл {last.meaningScore}/2 · Target {last.targetScore}/2</p></div>{canRetry&&drill&&<><div style={hintBox}><div style={small}>Self-repair</div><p style={{margin:'7px 0 0'}}>{last.meaningScore===2?turn.pattern.starterHint:drill.meaningHint}</p></div><button onClick={retryNow} style={{...primary,marginTop:14}}>Попробовать ещё раз →</button></>}{reveal&&drill&&<div style={model}><div style={small}>После двух попыток — модель</div><p style={{fontWeight:800,fontSize:19}}>“{drill.models[0]}”</p><p>Также естественно: “{drill.models[1]}”</p><code>{turn.pattern.form}</code><button onClick={next} style={{...primary,display:'block',marginTop:14}}>Продолжить →</button></div>}{(success||turn.free)&&<><div style={model}>{drill&&<><div style={small}>Ориентир после ответа</div><p style={{fontWeight:800,fontSize:19}}>“{drill.models[0]}”</p><p>Также естественно: “{drill.models[1]}”</p></>}</div><button onClick={next} style={{...primary,marginTop:14}}>{turnIndex<turns.length-1?'Дальше →':'Показать итог →'}</button></>}</section>}
  </div></main>
}

const page:React.CSSProperties={minHeight:'100vh',background:C.pale,color:C.ink,fontFamily:'system-ui,-apple-system,sans-serif'};const shell:React.CSSProperties={maxWidth:900,margin:'0 auto',padding:'42px 20px 72px'};const kicker:React.CSSProperties={margin:0,textTransform:'uppercase',letterSpacing:1.2,color:C.amber,fontWeight:850,fontSize:12};const hero:React.CSSProperties={color:C.navy,fontSize:'clamp(34px,7vw,56px)',lineHeight:1.08,margin:'10px 0 16px',letterSpacing:'-.02em'};const lead:React.CSSProperties={fontSize:17,lineHeight:1.65,maxWidth:760};const primary:React.CSSProperties={border:0,borderRadius:11,background:C.amber,color:C.navy,padding:'13px 18px',fontWeight:800,fontSize:15,cursor:'pointer'};const ghost:React.CSSProperties={border:'1px solid #d6d3d1',borderRadius:10,background:'transparent',color:C.muted,padding:'10px 13px',fontWeight:700,cursor:'pointer'};const patternCard:React.CSSProperties={textAlign:'left',border:`1px solid ${C.line}`,background:'white',borderRadius:15,padding:17,cursor:'pointer',fontFamily:'inherit'};const chip:React.CSSProperties={display:'inline-block',borderRadius:999,padding:'4px 8px',fontSize:11,fontWeight:800,background:'#eef4ff',color:C.navy};const notice:React.CSSProperties={border:'1px solid #bfd3ff',background:'#eef4ff',borderRadius:13,padding:'14px 16px',lineHeight:1.55};const hintBox:React.CSSProperties={marginTop:16,border:'1px solid #f5d487',background:'#fff7df',borderRadius:14,padding:16,lineHeight:1.5};const model:React.CSSProperties={marginTop:14,border:'1px solid #f5d487',background:'#fff7df',borderRadius:14,padding:17,lineHeight:1.5};const quote:React.CSSProperties={background:'white',border:`1px solid ${C.line}`,borderRadius:14,padding:17};const card:React.CSSProperties={background:'white',border:`1px solid ${C.line}`,borderRadius:14,padding:17,marginTop:12};const small:React.CSSProperties={textTransform:'uppercase',letterSpacing:1,color:C.muted,fontSize:11,fontWeight:850};const textarea:React.CSSProperties={width:'100%',boxSizing:'border-box',borderRadius:10,border:'1px solid #d6d3d1',padding:12,fontSize:16,fontFamily:'inherit'};const result:React.CSSProperties={background:'#172554',borderRadius:14,padding:17,display:'grid',gap:8};const summary:React.CSSProperties={marginTop:16,border:'1px solid #334155',background:'#111c3f',borderRadius:14,padding:18,lineHeight:1.6}
