'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { FR_PATTERNS } from './catalog'
import type { Drill, EvalOutcome, Pattern, Progress } from '../retrieval-lab-v2/types'

type Event = {
  patternId:string; drillId:string; phase:string; transcript:string; firstAttempt:boolean; hintLevel:number;
  meaningScore:0|1|2; targetScore:0|1|2; outcome:EvalOutcome; latencyMs:number; independent:boolean
}
type ProgressMap = Record<string,Progress>
type Turn = { pattern:Pattern; drill?:Drill; free?:boolean; interleaved?:boolean }
type SpeechRecognitionLike={lang:string;interimResults:boolean;continuous:boolean;maxAlternatives:number;start:()=>void;stop:()=>void;abort:()=>void;onstart:(()=>void)|null;onspeechstart:(()=>void)|null;onresult:((e:{results:ArrayLike<{0?:{transcript?:string}}>})=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null}

const C={navy:'#0f1b3d',amber:'#f59e0b',pale:'#fff8ed',ink:'#17213f',muted:'#667085',green:'#15803d',red:'#b42318',line:'#eadfce',blue:'#2563eb'}
const PK='ef_retrieval_fr_v2_progress'; const SK='ef_retrieval_fr_v2_resume'

function n(s:string){return s.toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[’‘]/g,"'").replace(/[^a-z0-9' ]+/g,' ').replace(/\s+/g,' ').trim()}
function meaning(d:Drill,raw:string):0|1|2{const t=n(raw);const hits=d.meaningGroups.filter(g=>g.some(x=>x.split('|').some(p=>t.includes(n(p))))).length;const r=hits/Math.max(1,d.meaningGroups.length);return r>=.72?2:r>=.34?1:0}
function evalAnswer(p:Pattern,d:Drill,text:string,first:boolean,hint:number,latency:number):Event{
  const t=n(text); const target:0|1|2=p.targetFull.test(t)?2:p.targetPartial.test(t)?1:0; const m=meaning(d,text); let outcome:EvalOutcome
  if(m===2&&target===2) outcome=first&&hint===0?'TARGET_INDEPENDENT':'TARGET_SUPPORTED'
  else if(m===2) outcome='MEANING_ALTERNATIVE'
  else if(m===1) outcome='MEANING_PARTIAL'
  else if(target>0) outcome='TARGET_NEEDS_REPAIR'
  else outcome='MEANING_MISS'
  return{patternId:p.id,drillId:d.id,phase:d.phase,transcript:text,firstAttempt:first,hintLevel:hint,meaningScore:m,targetScore:target,outcome,latencyMs:latency,independent:outcome==='TARGET_INDEPENDENT'}
}
function copy(e:Event){switch(e.outcome){case'TARGET_INDEPENDENT':return['Смысл и нужная французская форма получились','Это самостоятельное извлечение без подсказки.',C.green];case'TARGET_SUPPORTED':return['Получилось с поддержкой','Полезная практика, но пока не доказательство самостоятельного retrieval.',C.blue];case'MEANING_ALTERNATIVE':return['Смысл передан естественно','Но сейчас тренируем другой французский способ выразить эту мысль.',C.amber];case'MEANING_PARTIAL':return['Смысл передан частично','Уточним смысл и дадим минимальную подсказку.',C.amber];case'TARGET_NEEDS_REPAIR':return['Форма появилась, но смысл съехал','Нужно сохранить target и поправить содержание.',C.amber];default:return['Пока не получилось','Сначала поправим смысл, не показывая готовый ответ.',C.red]}}

export default function FrenchLab(){
  const[view,setView]=useState<'library'|'practice'|'result'>('library'); const[patternId,setPatternId]=useState(FR_PATTERNS[0].id); const[review,setReview]=useState(false)
  const[turnIndex,setTurnIndex]=useState(0); const[events,setEvents]=useState<Event[]>([]); const[progress,setProgress]=useState<ProgressMap>({}); const[retry,setRetry]=useState(0); const[hint,setHint]=useState(0)
  const[typed,setTyped]=useState(''); const[showTyped,setShowTyped]=useState(false); const[recording,setRecording]=useState(false); const[error,setError]=useState(''); const[resumeReady,setResumeReady]=useState(false)
  const shown=useRef(Date.now()); const speech=useRef<number|null>(null); const rec=useRef<SpeechRecognitionLike|null>(null)

  useEffect(()=>{try{const p=localStorage.getItem(PK);if(p)setProgress(JSON.parse(p));const s=localStorage.getItem(SK);if(s)setResumeReady(true)}catch{}},[])
  useEffect(()=>{shown.current=Date.now();speech.current=null;setTyped('');setShowTyped(false);setError('');try{rec.current?.abort()}catch{};rec.current=null;setRecording(false)},[turnIndex,retry,view])

  const focus=useMemo(()=>FR_PATTERNS.find(p=>p.id===patternId)!,[patternId])
  const oldPattern=useMemo(()=>{const id=Object.keys(progress).find(id=>id!==patternId);return id?FR_PATTERNS.find(p=>p.id===id)||null:null},[progress,patternId])
  const turns=useMemo<Turn[]>(()=>{const ds=review?focus.drills.filter(d=>['contrast','transfer','delayed'].includes(d.phase)):focus.drills;const list:Turn[]=ds.map(drill=>({pattern:focus,drill}));if(!review&&oldPattern){const od=oldPattern.drills.find(d=>d.phase==='delayed')||oldPattern.drills[oldPattern.drills.length-1];list.splice(Math.min(4,list.length),0,{pattern:oldPattern,drill:od,interleaved:true})}if(!review)list.push({pattern:focus,free:true});return list},[focus,oldPattern,review])
  const turn=turns[turnIndex]; const drill=turn?.drill; const current=drill?events.filter(e=>e.patternId===turn.pattern.id&&e.drillId===drill.id):events.filter(e=>e.patternId===turn?.pattern.id&&e.drillId==='free'); const last=current[current.length-1]

  useEffect(()=>{if(view==='practice')try{localStorage.setItem(SK,JSON.stringify({patternId,turnIndex,events,review}))}catch{}},[view,patternId,turnIndex,events,review])
  function persist(p:ProgressMap){setProgress(p);try{localStorage.setItem(PK,JSON.stringify(p))}catch{}}
  function start(id:string){const pr=progress[id];const due=!!pr&&new Date(pr.nextDueAt).getTime()<=Date.now();setPatternId(id);setReview(due);setTurnIndex(0);setEvents([]);setRetry(0);setHint(0);setView('practice')}
  function resume(){try{const raw=localStorage.getItem(SK);if(!raw)return;const x=JSON.parse(raw);if(!FR_PATTERNS.some(p=>p.id===x.patternId))return;setPatternId(x.patternId);setTurnIndex(x.turnIndex||0);setEvents(x.events||[]);setReview(!!x.review);setRetry(0);setHint(0);setView('practice')}catch{}}
  function recommended(){const due=FR_PATTERNS.find(p=>progress[p.id]&&new Date(progress[p.id].nextDueAt).getTime()<=Date.now());start((due||FR_PATTERNS.find(p=>!progress[p.id])||FR_PATTERNS[0]).id)}
  function next(){if(turnIndex<turns.length-1){setTurnIndex(i=>i+1);setRetry(0);setHint(0)}else finish()}
  function retryNow(){setRetry(r=>r+1);setHint(h=>Math.min(2,h+1))}
  function finish(){const xs=events.filter(e=>e.patternId===patternId);const delayed=xs.filter(e=>e.phase==='delayed').slice(-1)[0];const pass=delayed?.outcome==='TARGET_INDEPENDENT';const old=progress[patternId];const successes=(old?.delayedSuccesses||0)+(pass?1:0);const days=!pass?1:successes<=1?1:successes===2?3:successes===3?7:successes===4?14:30;const nextP={...progress,[patternId]:{sessions:(old?.sessions||0)+1,nextDueAt:new Date(Date.now()+days*86400000).toISOString(),delayedSuccesses:successes,lastOutcome:(xs[xs.length-1]?.outcome||null),lastValidProbeAt:xs.some(e=>e.independent)?new Date().toISOString():(old?.lastValidProbeAt||null)}};persist(nextP);try{localStorage.removeItem(SK)}catch{};setResumeReady(false);setView('result')}

  function submit(text:string,latency:number){if(!turn)return;if(turn.free){const t=n(text);const ts:0|1|2=turn.pattern.targetFull.test(t)?2:turn.pattern.targetPartial.test(t)?1:0;setEvents(x=>[...x,{patternId:turn.pattern.id,drillId:'free',phase:'free',transcript:text,firstAttempt:true,hintLevel:0,meaningScore:2,targetScore:ts,outcome:ts===2?'TARGET_INDEPENDENT':'MEANING_ALTERNATIVE',latencyMs:latency,independent:ts===2}]);return}if(!drill)return;setEvents(x=>[...x,evalAnswer(turn.pattern,drill,text,retry===0,hint,latency)])}
  function submitTyped(){const t=typed.trim();if(t)submit(t,Math.max(0,Date.now()-shown.current))}
  function voice(){setError('');const w=window as typeof window&{SpeechRecognition?:new()=>SpeechRecognitionLike;webkitSpeechRecognition?:new()=>SpeechRecognitionLike};const SR=w.SpeechRecognition||w.webkitSpeechRecognition;if(!SR){setShowTyped(true);setError('Голосовой ввод здесь не поддерживается. Используй текст.');return}try{const r=new SR();rec.current=r;r.lang='fr-FR';r.interimResults=false;r.continuous=false;r.maxAlternatives=1;r.onstart=()=>setRecording(true);r.onspeechstart=()=>{speech.current=Date.now()};r.onresult=e=>{const a=e.results[e.results.length-1];const t=a?.[0]?.transcript?.trim();setRecording(false);if(t)submit(t,Math.max(0,(speech.current||Date.now())-shown.current));else setError('Не расслышал. Попробуй ещё раз.')};r.onerror=()=>{setRecording(false);setShowTyped(true);setError('Голосовой ввод не сработал. Используй текст.')};r.onend=()=>setRecording(false);r.start()}catch{setShowTyped(true);setError('Не удалось запустить микрофон.')}}
  function stop(){try{rec.current?.stop()}catch{};setRecording(false)}

  if(view==='library'){const due=FR_PATTERNS.filter(p=>progress[p.id]&&new Date(progress[p.id].nextDueAt).getTime()<=Date.now()).length;return <main style={page}><div style={shell}><p style={kicker}>Français au Quotidien · Retrieval Lab V2</p><h1 style={hero}>Смысл → французская форма → self-repair → transfer.</h1><p style={lead}>Параллельная французская версия: 6 конструкций A2–B2, ситуации по-французски, минимальные подсказки, повторная попытка до model answer, blind transfer и короткие delayed-review.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:20}}><button onClick={recommended} style={primary}>Начать рекомендуемую →</button>{resumeReady&&<button onClick={resume} style={ghost}>Продолжить незавершённую</button>}</div><p style={{fontSize:13,color:C.muted}}>На повтор сегодня: {due}. Просроченные навыки идут раньше новых.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12,marginTop:24}}>{FR_PATTERNS.map(p=>{const pr=progress[p.id];const isDue=pr&&new Date(pr.nextDueAt).getTime()<=Date.now();return <button key={p.id} onClick={()=>start(p.id)} style={patternCard}><div style={{display:'flex',justifyContent:'space-between'}}><span style={chip}>{isDue?'Повторить сегодня':pr?`Проверка ${new Date(pr.nextDueAt).toLocaleDateString('ru-RU')}`:'Новый'}</span><span style={{fontSize:12,color:C.muted}}>{p.level}</span></div><strong style={{display:'block',marginTop:12,fontSize:18,color:C.navy}}>{p.name}</strong><span style={{display:'block',marginTop:6,fontSize:13,color:C.muted,lineHeight:1.5}}>{p.meaning}</span><code style={{display:'block',marginTop:10,fontSize:12}}>{p.form}</code></button>})}</div></div></main>}

  if(view==='result'){const xs=events.filter(e=>e.patternId===patternId);const first=xs.filter(e=>e.firstAttempt&&e.phase!=='free');const meaningOK=first.filter(e=>e.meaningScore===2).length;const targetOK=first.filter(e=>e.outcome==='TARGET_INDEPENDENT').length;const delayed=xs.filter(e=>e.phase==='delayed').slice(-1)[0];const supported=xs.filter(e=>e.outcome==='TARGET_SUPPORTED').length;const free=xs.find(e=>e.phase==='free');const pr=progress[patternId];return <main style={{...page,background:C.navy,color:'white'}}><div style={shell}><p style={{...kicker,color:'#fbbf24'}}>FR V2 · {focus.name}</p><h1 style={{...hero,color:'white'}}>Что действительно получилось без подсказки?</h1><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginTop:22}}><div style={result}><small>Смысл с первой попытки</small><strong>{meaningOK}/{first.length}</strong><span>мысль соответствовала ситуации</span></div><div style={result}><small>Нужная форма сама</small><strong>{targetOK}/{first.length}</strong><span>без подсказки и без показанной модели</span></div><div style={result}><small>Delayed-in-session probe</small><strong>{delayed?.outcome==='TARGET_INDEPENDENT'?'Получился':'Не подтверждён'}</strong><span>важный сигнал внутри этой сессии</span></div><div style={result}><small>С поддержкой</small><strong>{supported}</strong><span>полезная практика, но не mastery evidence</span></div></div>{free&&<div style={summary}><strong>Свободная речь</strong><p style={{margin:'8px 0 0',color:'#cbd5e1'}}>{free.targetScore===2?'Target появился спонтанно.':'Target не появился — и это не ошибка: в free task он не обязателен.'}</p></div>}<div style={summary}><strong>Сохранение навыка ещё не доказано.</strong><p style={{margin:'8px 0 0',color:'#cbd5e1'}}>Следующая короткая проверка: {pr?new Date(pr.nextDueAt).toLocaleDateString('ru-RU'):'—'}. Только delayed success расширяет интервал.</p></div><button onClick={()=>setView('library')} style={{...primary,marginTop:20}}>Закончить</button></div></main>}

  if(!turn)return null; const cp=last?copy(last):null; const success=!!last&&(last.outcome==='TARGET_INDEPENDENT'||last.outcome==='TARGET_SUPPORTED'); const canRetry=!!last&&!success&&retry<2; const reveal=!!last&&!success&&retry>=2; const phase=turn.interleaved?'Interleaving · старый навык':turn.free?'Free production · target не обязателен':review?'Короткий delayed review':drill?.phase==='cold'?'Cold probe · target скрыт':drill?.phase==='runway'?'Blocked runway':drill?.phase==='contrast'?'Contrast boundary':drill?.phase==='transfer'?'Blind transfer':drill?.phase==='delayed'?'Delayed-in-session':'Varied retrieval'
  return <main style={page}><div style={shell}><button onClick={()=>setView('library')} style={ghost}>← Библиотека</button><p style={{...kicker,marginTop:24}}>{phase}</p><h2 style={{fontSize:20,color:C.muted,margin:'8px 0'}}>{turn.pattern.name}</h2>{!turn.free&&drill&&<><div style={scenario}>{drill.scenario}</div><h1 style={{...hero,fontSize:'clamp(28px,6vw,42px)'}}>{drill.prompt}</h1></>}{turn.free&&<><div style={scenario}>Говори свободно 20–30 секунд. Нужная конструкция может появиться сама, но заставлять её не нужно.</div><h1 style={{...hero,fontSize:'clamp(28px,6vw,42px)'}}>{turn.pattern.freePrompt}</h1></>}
  {retry>0&&drill&&<div style={hintBox}><b>{retry===1?'Минимальная подсказка':'Более явная подсказка'}</b><p>{retry===1?drill.meaningHint:turn.pattern.formHint}</p>{retry>=2&&<code>{turn.pattern.form}</code>}</div>}
  {!last&&<div style={{marginTop:24}}><button onClick={recording?stop:voice} style={{...primary,background:recording?C.red:C.navy,color:'white'}}>{recording?'■ Остановить':'🎙 Ответить по-французски'}</button><button onClick={()=>setShowTyped(v=>!v)} style={{...ghost,marginLeft:10}}>Или напечатать</button>{showTyped&&<div style={{marginTop:14}}><textarea value={typed} onChange={e=>setTyped(e.target.value)} rows={3} placeholder="Réponse en français…" style={textarea}/><button onClick={submitTyped} style={{...primary,marginTop:8}}>Проверить</button></div>}{error&&<p style={{color:C.red}}>{error}</p>}</div>}
  {last&&cp&&<div style={{marginTop:24}}><div style={answer}><small>Ты сказал</small><p style={{fontSize:19}}>«{last.transcript}»</p></div><div style={{...feedback,borderLeft:`5px solid ${cp[2]}`}}><strong>{cp[0]}</strong><p>{cp[1]}</p></div>{canRetry&&<button onClick={retryNow} style={{...primary,marginTop:12}}>Попробовать ещё раз с подсказкой →</button>}{(success||reveal)&&<><div style={model}><small>Рекомендуемый вариант</small><p><b>«{drill?.models[0]||'—'}»</b></p>{drill?.models[1]&&<><small>Также естественно</small><p>«{drill.models[1]}»</p></>}</div><button onClick={next} style={{...primary,marginTop:12}}>{turnIndex<turns.length-1?'Дальше →':'Показать итог →'}</button></>}</div>}
  </div></main>
}

const page:React.CSSProperties={minHeight:'100vh',background:C.pale,color:C.ink,fontFamily:'system-ui,-apple-system,sans-serif'}
const shell:React.CSSProperties={maxWidth:900,margin:'0 auto',padding:'42px 20px 72px'}
const kicker:React.CSSProperties={margin:0,textTransform:'uppercase',letterSpacing:1.2,color:C.amber,fontSize:12,fontWeight:850}
const hero:React.CSSProperties={color:C.navy,fontSize:'clamp(34px,7vw,54px)',lineHeight:1.08,margin:'10px 0 18px'}
const lead:React.CSSProperties={fontSize:17,lineHeight:1.6,color:C.muted}
const primary:React.CSSProperties={border:0,borderRadius:10,background:C.amber,color:C.navy,padding:'13px 18px',fontWeight:800,fontSize:15,cursor:'pointer'}
const ghost:React.CSSProperties={border:'1px solid #d6d3d1',borderRadius:10,background:'transparent',color:C.muted,padding:'10px 13px',fontWeight:700,cursor:'pointer'}
const patternCard:React.CSSProperties={textAlign:'left',border:`1px solid ${C.line}`,background:'white',borderRadius:14,padding:16,cursor:'pointer',fontFamily:'inherit'}
const chip:React.CSSProperties={background:'#eef4ff',borderRadius:999,padding:'4px 8px',fontSize:11,fontWeight:800,color:C.navy}
const scenario:React.CSSProperties={marginTop:18,padding:16,border:`1px solid ${C.line}`,background:'white',borderRadius:14,fontSize:17,lineHeight:1.55}
const hintBox:React.CSSProperties={marginTop:16,padding:16,border:'1px solid #f5d487',background:'#fff7df',borderRadius:14,lineHeight:1.5}
const textarea:React.CSSProperties={width:'100%',boxSizing:'border-box',border:'1px solid #d6d3d1',borderRadius:10,padding:12,fontSize:16}
const answer:React.CSSProperties={background:'white',border:`1px solid ${C.line}`,borderRadius:14,padding:16}
const feedback:React.CSSProperties={background:'white',border:`1px solid ${C.line}`,borderRadius:14,padding:16,marginTop:10}
const model:React.CSSProperties={background:'#fff7df',border:'1px solid #f5d487',borderRadius:14,padding:16,marginTop:12}
const result:React.CSSProperties={background:'#172554',borderRadius:14,padding:16,display:'grid',gap:8}
const summary:React.CSSProperties={marginTop:16,padding:18,border:'1px solid #334155',borderRadius:14,background:'#111c3f'}
